# Generated by Django 5.1.7 on 2025-03-11 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='image_urls',
            field=models.ImageField(upload_to=''),
        ),
    ]
