# Generated by Django 5.1.7 on 2025-03-12 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_place_place_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='details_url',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
