# Generated by Django 5.1.7 on 2025-03-13 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0008_alter_image_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='preview',
            field=models.ImageField(default='none', upload_to='images/', verbose_name='GET PREVIEW'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(default='none', upload_to='images/', verbose_name='Картинка'),
        ),
    ]
