# Generated by Django 5.1.7 on 2025-03-13 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0010_alter_place_options_remove_image_preview_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='place',
            options={},
        ),
        migrations.RemoveField(
            model_name='place',
            name='my_order',
        ),
        migrations.AddField(
            model_name='image',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
