# Generated by Django 5.1.7 on 2025-03-13 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0011_alter_image_options_alter_place_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='place',
            options={'ordering': ['title']},
        ),
    ]
