# Generated by Django 5.1.7 on 2025-03-13 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0014_remove_place_details_url_alter_image_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='place',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='place',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
