# Generated by Django 5.1.7 on 2025-03-14 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0015_alter_place_options_place_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='place_id',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
