# Generated by Django 5.1.7 on 2025-04-01 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0020_alter_place_long_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='порядок'),
        ),
        migrations.AlterField(
            model_name='place',
            name='title',
            field=models.CharField(max_length=150, unique=True, verbose_name='Название места'),
        ),
    ]
